name: biometric-env
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - matplotlib
  - scikit-learn
  - opencv
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - kagglehub
  - tqdm
  - gdown
  - reedsolo
  - pip:
      - tensorboard
